version: '3'
services:
  node:
    build:
      context: .
      dockerfile: "./docker/nodejs/Dockerfile"
    container_name: "test_webserver"
    restart: 'always'
    ports:
      - "80:3000"
    volumes:
      - ./:/app
  mongodb:
    image: mongo
    container_name: "test_app_database"
    restart: 'always'
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: Users
    volumes:
      - ./mongodb_data:/data/db
